### ISSUE TITLE
T2: Create UI 1/2

### ISSUE THREAD

**Issue by sevvalyurtseven** [sevvalyurtseven/E-Commerce-Project#2]
- Create Figma Designs: [Figma-Ecommerce-UI-Kit-(Demo-Version)-(Community)](https://www.figma.com/file/tXhNJv706AWM0lXlyxLH9l/E-commerce-UI---Figma-Ecommerce-UI-Kit-(Demo-Version)-(Community))
- Use only **Flex** Layout
- Use only **Tailwind classes, no custom classes allowed!**
    - Check **Customizing Theme and Arbitrary** [values on Tailwind](https://tailwindcss.com/docs/adding-custom-styles#using-arbitrary-values)
    - Check **@apply** [directive usage on Tailwind](https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply)

- [x] Create Layout Components like: **Header, PageContent,  Footer 
NOTE! There should be only ONE Header, Footer components for all pages, no color changes needed!**

Create Page Components (**Only Desktop Views**): **Home, Product List**
- [x] Create repetitive Components like: **ProductCard, CategoryCard**
- [x] Home Page: Slider component
    - [x] Find a slider component can be used in React JS
- [x] Activate **React Router and Links** for Home and Shopping links
- [x] Use an **Icon Library** like: FontAwesome (CDN is recommended)

**Comment by sevvalyurtseven** [comment]
@gokhanozdemir slider'im da bir sorun vaaar. mainslider componentinde olusturdum kendisini

**Comment by sevvalyurtseven** [comment]
https://github.com/sevvalyurtseven/E-Commerce-Project/blob/main/my-react-project/src/components/MainSlider.js

**Comment by gokhanozdemir** [comment]
![ezgif com-video-to-gif-converted (1)](https://github.com/sevvalyurtseven/E-Commerce-Project/assets/8511119/0a0f30d2-0276-4331-9143-947f6b7c1c35)
can not recreate issue. Chrome (Version 120.0.6099.109 (Official Build) (arm64)) ve Safari (119.0 (64-bit))
çözüm önerisi olarak node modules kaldırıp yeniden kurmayı önerebilirim. Arada slide için kurulan bazı paketlerin sürümleri bir şekilde çakışmış olabilir.

**Comment by sevvalyurtseven** [comment]
Home Page: 
- Figma Designs: [Figma-Ecommerce-UI-Kit-(Demo-Version)-(Community)](https://www.figma.com/file/tXhNJv706AWM0lXlyxLH9l/E-commerce-UI---Figma-Ecommerce-UI-Kit-(Demo-Version)-(Community))
- Use only `Flex Layout`
- Use only `Tailwind` classes, **no custom classes allowed!**
    - Check [**Customizing Theme and Arbitrary** values on Tailwind](https://tailwindcss.com/docs/adding-custom-styles#using-arbitrary-values)
    - Check [**@apply** directive usage on Tailwind](https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply)
    - Check [**Tailwind responsive solution:**](https://tailwindcss.com/docs/responsive-design)
    - Check [**Tailwind switch breakpoints min to max responsive solution:**](https://tailwindcss.com/docs/screens#max-width-breakpoints)

- [ ] Create Layout Components like: 
    - [ ] Header
**NOTE! There should be only ONE HEADER COMPONENT and ONE MENU for all pages, no color changes needed!**
    - [ ] PageContent
(PageContent means a layout container that holds page components and routing definitions)
    - [ ] Footer 


- [ ] Create Home Page Component Desktop View

- [ ] Create Home Page Component Mobile View

- [ ] Create repetitive Components like: **ProductCard**

- [ ] Slider component
    - [ ] Find a slider component can be used in React JS
    - [ ] Implement it to Home Page

- [ ] Activate **React Router and Links** for Home Page

- [ ] Use an **Icon Library** like: FontAwesome (CDN is recommended)


Your folder tree should be like 

```
src/
   components/
       ProductCard.js
   layout/
       Header.js
       PageContent.js
       Footer.js
   pages/
       HomePage.js
       ...
```
